import { createContext, useContext, useEffect, useState, ReactNode } from "react";

/* ---------------- Theme ---------------- */
type Theme = "light" | "dark";
type ThemeCtx = { theme: Theme; toggle: () => void };
const ThemeContext = createContext<ThemeCtx>({ theme: "dark", toggle: () => {} });

export function ThemeProvider({ children }: { children: ReactNode }) {
  const [theme, setTheme] = useState<Theme>("dark");

  useEffect(() => {
    const saved = (typeof window !== "undefined" && localStorage.getItem("theme")) as Theme | null;
    const initial: Theme = saved ?? (window.matchMedia("(prefers-color-scheme: light)").matches ? "light" : "dark");
    setTheme(initial);
  }, []);

  useEffect(() => {
    const root = document.documentElement;
    root.classList.remove("light", "dark");
    root.classList.add(theme);
    try { localStorage.setItem("theme", theme); } catch {}
  }, [theme]);

  return (
    <ThemeContext.Provider value={{ theme, toggle: () => setTheme((t) => (t === "dark" ? "light" : "dark")) }}>
      {children}
    </ThemeContext.Provider>
  );
}
export const useTheme = () => useContext(ThemeContext);

/* ---------------- i18n ---------------- */
type Lang = "fr" | "en";
type I18nCtx = { lang: Lang; setLang: (l: Lang) => void; t: (k: string) => string };
const I18nContext = createContext<I18nCtx>({ lang: "fr", setLang: () => {}, t: (k) => k });

const dict: Record<Lang, Record<string, string>> = {
  fr: {
    "nav.program": "Programme",
    "nav.agenda": "Agenda",
    "nav.schedule": "Calendrier",
    "nav.trainers": "Formateurs",
   "nav.contacts": "Contacts",
   "nav.participants": "Participants",
   "nav.projects": "Projets",
    "pp.kicker": "Hackathon",
    "pp.title": "Projets des équipes",
    "pp.subtitle": "Les solutions construites par les participants pendant le bootcamp.",
    "pp.empty": "Aucun projet publié pour le moment.",
    "proj.makePublic": "Rendre public",
    "proj.makePrivate": "Retirer du public",
    "proj.isPublic": "Public",
    "nav.dashboard": "Dashboard",
    "nav.register": "⚡ S'inscrire",
    "footer.contact": "Contact",
    "footer.partners": "Partenaires",
    "footer.partners.body": "Vexl — P2P Bitcoin trading\nFree Tech Institute",
    "footer.copy": "© 2026 Free Tech Institute. Peer-to-Peer Bitcoin Educational Program.",
    "hero.badge": "Université Polytechnique de Gitega · 21–25 septembre 2026",
    "hero.title1": "Bitcoin",
    "hero.title2": "Bootcamp",
    "hero.subtitle": "30 jeunes Burundais répartis en équipes, cinq jours de 15h à 19h, une approche 100% pratique. Bitcoin, Lightning Network, API Blink et passerelles mobile money Lumicash et Afripay, puis le hackathon.",
    "hero.apply": "Postuler maintenant",
    "hero.discover": "Découvrir le programme",
    "stat.participants": "Participants",
    "stat.hackathons": "Jours",
    "stat.workshops": "Équipes",
    "stat.prize": "Équipes primées",
    "program.kicker": "// Programme",
    "program.title": "La technologie est un moyen, jamais une fin",
    "program.subtitle": "Trois jours de formation puis deux jours de hackathon. Chaque module part d'un besoin réel du terrain burundais avant d'introduire l'outil technique.",
    "prog.1.t": "Fondamentaux Bitcoin",
    "prog.1.d": "Décentralisation et consensus. L'on-chain est présenté à titre informatif uniquement.",
    "prog.2.t": "Lightning & API Blink",
    "prog.2.d": "Paiements instantanés, création de wallets et paiements réels via l'API Blink.",
    "prog.3.t": "Sécurité & confiance",
    "prog.3.d": "Clés privées, auto-garde, puis concevoir des applications décentralisées pour de vrais utilisateurs.",
    "prog.4.t": "Mobile money & hackathon",
    "prog.4.d": "Lumicash et Afripay comme ponts locaux, puis prototype en équipe et Demo Day.",
    "sched.kicker": "// Calendrier",
    "sched.title": "Cinq jours à Gitega, de 15h à 19h",
    "sched.month": "SEPT 2026",
    "sched.h1.t": "Formations — 3 jours",
    "sched.h1.s": "Bitcoin, Lightning et API Blink, sécurité et confiance, Lumicash et Afripay",
    "sched.h2.t": "Hackathon & Demo Day",
    "sched.h2.s": "Des équipes accompagnées par un mentor, des pitchs devant le jury et une graduation",
    "sched.prizes": "🏆 Les deux meilleurs projets sont récompensés",
    "trainers.kicker": "// Formateurs",
    "trainers.title": "L'équipe",
    "trainers.soon": "Les formateurs seront bientôt annoncés.",
    "trainers.lead": "Lead Trainer · Free Tech Institute",
    "trainers.role": "Trainer · Free Tech Institute",
    "trainers.bio.advaxe": "Passionné par l'éducation Bitcoin et le développement communautaire en Afrique.",
    "trainers.bio.belyi": "Expert en développement logiciel et applications décentralisées.",
    "trainers.bio.wilfried": "Spécialiste en sécurité et infrastructure réseau.",
    "speakers.admin.title": "Gestion des speakers",
    "speakers.add": "Ajouter",
    "speakers.delete": "Supprimer",
    "speakers.confirmDelete": "Supprimer ce speaker ?",
    "speakers.uploadAvatar": "Changer la photo",
    "speakers.uploading": "Upload",
    "speakers.name": "Nom",
    "speakers.role": "Rôle",
    "speakers.bio": "Bio",
    "speakers.twitter": "X / Twitter",
    "speakers.order": "Ordre",
    "speakers.save": "Enregistrer",
    "speakers.saving": "...",
    "sa.title": "Programme des journées",
    "sa.day": "Jour",
    "sa.add": "Ajouter un créneau",
    "sa.empty": "Aucun créneau pour le moment",
    "sa.start": "Début",
    "sa.end": "Fin",
    "sa.titleField": "Titre",
    "sa.theme": "Thème",
    "sa.speaker": "Intervenant",
    "sa.noSpeaker": "Aucun",
    "sa.order": "Ordre",
    "sa.delete": "Supprimer",
    "sa.confirmDelete": "Supprimer ce créneau ?",
    "agenda.kicker": "// Agenda détaillé",
    "agenda.title": "Programme jour par jour",
    "agenda.subtitle": "Heure par heure, retrouvez les thèmes et intervenants de chaque créneau.",
    "agenda.day1": "Jour 1",
    "agenda.day2": "Jour 2",
    "agenda.day": "Jour",
    "agenda.empty": "Programme en cours de finalisation",
    "agenda.by": "par",
    "ed.kicker": "// Éditions",
    "ed.title": "Choisissez votre édition",
    "ed.subtitle": "Le programme, les intervenants et les inscriptions changent selon l'édition sélectionnée.",
    "ed.highlights": "Au programme",
    "ed.dates": "Dates",
    "ed.venue": "Lieu",
    "ed.soon": "Prochainement",

    "out.kicker": "// Objectifs",
    "out.title": "Résultats attendus",
    "out.1": "30 participants formés & certifiés",
    "out.2": "2 prototypes Bitcoin/Lightning P2P développés",
    "out.3": "70% capables d'utiliser Bitcoin et des applications Lightning",
    "out.4": "10+ transactions peer-to-peer réalisées pendant les exercices",
    "out.5": "Une contribution concrète à l'écosystème Bitcoin burundais",
    "cta.title": "Rejoignez la cohorte",
    "sel.kicker": "// Promotion 2026",
    "sel.title": "Participants sélectionnés",
    "sel.subtitle": "Les candidats retenus pour le Bootcamp Bitcoin de Gitega.",
    "cta.spots": "Inscriptions ouvertes à tous · 30 participants seront retenus.",
    "cta.received": "candidature(s) reçue(s).",
    "cta.apply": "Déposer ma candidature",
    "contact.subtitle": "Une question ? Écrivez-nous.",
    "cta.dashboard": "Voir le dashboard",
    "back": "Retour",
    "reg.kicker": "// Candidature",
    "reg.title": "Inscription au BOOTCAMP GITEGA",
    "reg.subtitle": "Inscriptions ouvertes à tous : 30 candidats seront retenus. Du 21 au 25 septembre 2026, de 15h à 19h, à l'Université Polytechnique de Gitega.",
    "reg.cohort": "Édition *",
    "reg.cohort.help": "Gitega (Université Polytechnique de Gitega).",
    "reg.group": "Groupe d'appartenance *",
    "reg.group.ph": "Université, association, entreprise, communauté…",
    "reg.avail": "Disponibilité *",
    "reg.avail.help": "Je confirme être disponible les 5 jours, du 21 au 25 septembre 2026, de 15h à 19h.",
    "reg.laptop": "Ordinateur portable",
    "reg.laptop.help": "Je viendrai avec mon ordinateur portable pour les ateliers pratiques.",
    "reg.problem": "Problème réel à résoudre",
    "reg.problem.ph": "Quel problème concret de votre entourage aimeriez-vous résoudre avec Bitcoin, Lightning ou le mobile money ?",

    "reg.full_name": "Nom complet *",
    "reg.email": "Email *",
    "reg.phone": "Téléphone",
    "reg.profession": "Profession / Étudiant en",
    "reg.level": "Niveau en Bitcoin/Dev *",
    "reg.hack": "Hackathon visé *",
    "reg.motivation": "Motivation",
    "reg.motivation.ph": "Pourquoi voulez-vous participer ? Quel projet aimeriez-vous construire ?",
    "reg.submit": "Envoyer ma candidature",
    "reg.submitting": "Envoi...",
    "reg.success": "Candidature envoyée ! Nous reviendrons vers vous bientôt.",
    "reg.deadline": "Date limite d'inscription : dimanche 20 septembre 2026 à 23h59.",
    "reg.closed.title": "Les inscriptions sont closes",
    "reg.closed.help": "La date limite était le dimanche 20 septembre 2026. Merci de votre intérêt !",
    "proj.kicker": "// Dépôt des projets",
    "proj.title": "Soumettre votre projet",
    "proj.subtitle": "Pendant le hackathon, déposez ici le projet de votre équipe : liens, aperçu, présentation et documentation.",
    "proj.team": "Nom de l'équipe *",
    "proj.email": "E-mail de contact *",
    "proj.members": "Membres de l'équipe",
    "proj.members.ph": "Noms séparés par des virgules",
    "proj.desc": "Description du projet",
    "proj.desc.ph": "Quel problème résolvez-vous et comment ?",
    "proj.web": "Lien web (démo)",
    "proj.github": "Lien GitHub",
    "proj.docs": "Lien de la documentation",
    "proj.image": "Image d'aperçu",
    "proj.image.help": "PNG ou JPG, 5 Mo maximum",
    "proj.slides": "Présentation (PDF)",
    "proj.slides.help": "Votre PowerPoint exporté en PDF, 25 Mo maximum",
    "proj.submit": "Envoyer le projet",
    "proj.submitting": "Envoi...",
    "proj.success": "Projet envoyé ! Bonne chance pour le Demo Day.",
    "proj.uploading": "Téléversement du fichier...",
    "proj.admin.title": "// Projets soumis",
    "proj.admin.empty": "Aucun projet soumis pour le moment",
    "proj.admin.open": "Ouvrir",
    "proj.admin.delete": "Supprimer ce projet ?",
    "level.beginner": "Débutant",
    "level.intermediate": "Intermédiaire",
    "level.advanced": "Avancé",
    "hack.both": "Les deux (5 & 6 juin)",
    "hack.1": "Hackathon #1 — 5 juin",
    "hack.2": "Hackathon #2 — 6 juin",
    "hack.both.short": "Les deux",
    "reg.role": "Spécialité développeur *",
    "reg.role.ph": "Choisir une spécialité",
    "role.backend": "Backend",
    "role.frontend": "Frontend",
    "role.fullstack": "Full Stack",
    "reg.langs": "Langages maîtrisés",
    "reg.langs.help": "Sélectionnez tous ceux que vous utilisez",
    "dash.kicker": "// Suivi des candidatures",
    "dash.title": "Dashboard",
    "dash.subtitle": "Gestion des inscriptions au BOOTCAMP GITEGA",
    "dash.new": "+ Nouvelle inscription",
    "dash.logout": "Déconnexion",
    "kpi.total": "Candidatures",
    "kpi.accepted": "Acceptées",
    "kpi.pending": "En attente",
    "kpi.spots": "Places restantes",
    "chart.hack": "Profil des candidats",
    "chart.level": "Niveau d'expérience",
    "table.title": "Toutes les candidatures",
    "table.search": "Rechercher (nom, e-mail, groupe, profil, statut…)",
    "table.export.sheet": "Candidatures",
    "filter.all": "Tout",
    "filter.pending": "En attente",
    "filter.accepted": "Acceptées",
    "filter.waitlist": "Liste d'attente",
    "filter.rejected": "Refusées",
    "loading": "Chargement...",
    "table.empty": "Aucune candidature",
    "th.candidate": "Candidat",
    "th.level": "Niveau",
    "th.hackathon": "Profil",
    "th.avail": "Dispo. 5 jours",
    "th.laptop": "PC portable",
    "yes": "Oui",
    "no": "Non",
    "th.group": "Groupe",
    "th.date": "Date",
    "th.status": "Statut",
    "status.pending": "En attente",
    "status.accepted": "Accepté",
    "status.waitlist": "Liste d'attente",
    "status.rejected": "Refusé",
    "login.kicker": "// Admin",
    "login.title": "Connexion",
    "login.subtitle": "Accès réservé aux organisateurs du BOOTCAMP GITEGA.",
    "login.email": "Email",
    "login.password": "Mot de passe",
    "login.submit": "Se connecter",
    "login.submitting": "Connexion...",
    "login.success": "Connecté !",
  },
  en: {
    "nav.program": "Program",
    "nav.agenda": "Agenda",
    "nav.schedule": "Schedule",
    "nav.trainers": "Trainers",
   "nav.contacts": "Contact",
   "nav.participants": "Participants",
   "nav.projects": "Projects",
    "pp.kicker": "Hackathon",
    "pp.title": "Team projects",
    "pp.subtitle": "The solutions built by participants during the bootcamp.",
    "pp.empty": "No project published yet.",
    "proj.makePublic": "Make public",
    "proj.makePrivate": "Make private",
    "proj.isPublic": "Public",
    "nav.dashboard": "Dashboard",
    "nav.register": "⚡ Apply",
    "footer.contact": "Contact",
    "footer.partners": "Partners",
    "footer.partners.body": "Vexl — P2P Bitcoin trading\nFree Tech Institute",
    "footer.copy": "© 2026 Free Tech Institute. Peer-to-Peer Bitcoin Educational Program.",
    "hero.badge": "Université Polytechnique de Gitega · September 21–25, 2026",
    "hero.title1": "Bitcoin",
    "hero.title2": "Bootcamp",
    "hero.subtitle": "30 young Burundians working in teams, five days from 3 to 7 PM, a fully hands-on approach. Bitcoin, Lightning Network, the Blink API and the Lumicash and Afripay mobile money gateways, then the hackathon.",
    "hero.apply": "Apply now",
    "hero.discover": "Explore the program",
    "stat.participants": "Participants",
    "stat.hackathons": "Days",
    "stat.workshops": "Teams",
    "stat.prize": "Winning teams",
    "program.kicker": "// Program",
    "program.title": "Technology is a means, never an end",
    "program.subtitle": "Three days of training, then two days of hackathon. Every module starts from a real Burundian need before introducing the technical tool.",
    "prog.1.t": "Bitcoin fundamentals",
    "prog.1.d": "Decentralization and consensus. On-chain is covered for information only.",
    "prog.2.t": "Lightning & Blink API",
    "prog.2.d": "Instant payments, wallet creation and real Lightning payments via the Blink API.",
    "prog.3.t": "Security & trust",
    "prog.3.d": "Private keys, self-custody, then designing decentralized apps for real users.",
    "prog.4.t": "Mobile money & hackathon",
    "prog.4.d": "Lumicash and Afripay as local bridges, then team prototypes and Demo Day.",
    "sched.kicker": "// Schedule",
    "sched.title": "Five days in Gitega, 3 to 7 PM",
    "sched.month": "SEPT 2026",
    "sched.h1.t": "Training — 3 days",
    "sched.h1.s": "Bitcoin, Lightning and the Blink API, security and trust, Lumicash and Afripay",
    "sched.h2.t": "Hackathon & Demo Day",
    "sched.h2.s": "Teams supported by mentors, jury pitches and graduation",
    "sched.prizes": "🏆 The top two projects are rewarded",
    "trainers.kicker": "// Trainers",
    "trainers.title": "The team",
    "trainers.soon": "The trainers will be announced soon.",
    "trainers.lead": "Lead Trainer · Free Tech Institute",
    "trainers.role": "Trainer · Free Tech Institute",
    "trainers.bio.advaxe": "Passionate about Bitcoin education and community development in Africa.",
    "trainers.bio.belyi": "Expert in software development and decentralized applications.",
    "trainers.bio.wilfried": "Specialist in security and network infrastructure.",
    "speakers.admin.title": "Speakers management",
    "speakers.add": "Add",
    "speakers.delete": "Delete",
    "speakers.confirmDelete": "Delete this speaker?",
    "speakers.uploadAvatar": "Change photo",
    "speakers.uploading": "Uploading",
    "speakers.name": "Name",
    "speakers.role": "Role",
    "speakers.bio": "Bio",
    "speakers.twitter": "X / Twitter",
    "speakers.order": "Order",
    "speakers.save": "Save",
    "speakers.saving": "...",
    "sa.title": "Day-by-day program",
    "sa.day": "Day",
    "sa.add": "Add slot",
    "sa.empty": "No slot yet",
    "sa.start": "Start",
    "sa.end": "End",
    "sa.titleField": "Title",
    "sa.theme": "Theme",
    "sa.speaker": "Speaker",
    "sa.noSpeaker": "None",
    "sa.order": "Order",
    "sa.delete": "Delete",
    "sa.confirmDelete": "Delete this slot?",
    "agenda.kicker": "// Detailed agenda",
    "agenda.title": "Day-by-day program",
    "agenda.subtitle": "Hour-by-hour themes and speakers for every slot.",
    "agenda.day1": "Day 1",
    "agenda.day2": "Day 2",
    "agenda.day": "Day",
    "agenda.empty": "Program coming soon",
    "agenda.by": "by",
    "ed.kicker": "// Editions",
    "ed.title": "Choose your edition",
    "ed.subtitle": "Program, speakers and registration change with the selected edition.",
    "ed.highlights": "What's included",
    "ed.dates": "Dates",
    "ed.venue": "Venue",
    "ed.soon": "Coming up",

    "out.kicker": "// Outcomes",
    "out.title": "Expected outcomes",
    "out.1": "30 trained & certified participants",
    "out.2": "2 Bitcoin/Lightning P2P prototypes built",
    "out.3": "70% able to use Bitcoin and Lightning applications",
    "out.4": "10+ peer-to-peer transactions during the exercises",
    "out.5": "A concrete contribution to Burundi's Bitcoin ecosystem",
    "cta.title": "Join the cohort",
    "sel.kicker": "// Class of 2026",
    "sel.title": "Selected participants",
    "sel.subtitle": "The candidates selected for the Gitega Bitcoin Bootcamp.",
    "cta.spots": "Open to everyone · 30 participants will be selected.",
    "cta.received": "application(s) received.",
    "cta.apply": "Submit my application",
    "contact.subtitle": "A question? Write to us.",
    "cta.dashboard": "View dashboard",
    "back": "Back",
    "reg.kicker": "// Application",
    "reg.title": "BOOTCAMP GITEGA registration",
    "reg.subtitle": "Open to everyone: 30 candidates will be selected. September 21–25, 2026, 3 to 7 PM, at Université Polytechnique de Gitega.",
    "reg.cohort": "Edition *",
    "reg.cohort.help": "Gitega (Université Polytechnique de Gitega).",
    "reg.group": "Group you belong to *",
    "reg.group.ph": "University, association, company, community…",
    "reg.avail": "Availability *",
    "reg.avail.help": "I confirm I am available all 5 days, September 21–25, 2026, from 3 to 7 PM.",
    "reg.laptop": "Laptop",
    "reg.laptop.help": "I will bring my own laptop for the hands-on workshops.",
    "reg.problem": "Real problem to solve",
    "reg.problem.ph": "What concrete problem around you would you like to solve with Bitcoin, Lightning or mobile money?",

    "reg.full_name": "Full name *",
    "reg.email": "Email *",
    "reg.phone": "Phone",
    "reg.profession": "Profession / Student in",
    "reg.level": "Bitcoin/Dev level *",
    "reg.hack": "Target hackathon *",
    "reg.motivation": "Motivation",
    "reg.motivation.ph": "Why do you want to join? What would you like to build?",
    "reg.submit": "Send my application",
    "reg.submitting": "Sending...",
    "reg.success": "Application sent! We'll get back to you soon.",
    "reg.deadline": "Registration deadline: Sunday, September 20, 2026 at 11:59 PM.",
    "reg.closed.title": "Registrations are closed",
    "reg.closed.help": "The deadline was Sunday, September 20, 2026. Thank you for your interest!",
    "proj.kicker": "// Project submission",
    "proj.title": "Submit your project",
    "proj.subtitle": "During the hackathon, submit your team's project here: links, preview, slides and documentation.",
    "proj.team": "Team name *",
    "proj.email": "Contact email *",
    "proj.members": "Team members",
    "proj.members.ph": "Names separated by commas",
    "proj.desc": "Project description",
    "proj.desc.ph": "What problem do you solve, and how?",
    "proj.web": "Web link (demo)",
    "proj.github": "GitHub link",
    "proj.docs": "Documentation link",
    "proj.image": "Preview image",
    "proj.image.help": "PNG or JPG, 5 MB max",
    "proj.slides": "Slides (PDF)",
    "proj.slides.help": "Your PowerPoint exported as PDF, 25 MB max",
    "proj.submit": "Submit project",
    "proj.submitting": "Sending...",
    "proj.success": "Project submitted! Good luck on Demo Day.",
    "proj.uploading": "Uploading file...",
    "proj.admin.title": "// Submitted projects",
    "proj.admin.empty": "No project submitted yet",
    "proj.admin.open": "Open",
    "proj.admin.delete": "Delete this project?",
    "level.beginner": "Beginner",
    "level.intermediate": "Intermediate",
    "level.advanced": "Advanced",
    "hack.both": "Both (June 5 & 6)",
    "hack.1": "Hackathon #1 — June 5",
    "hack.2": "Hackathon #2 — June 6",
    "hack.both.short": "Both",
    "reg.role": "Developer specialty *",
    "reg.role.ph": "Choose a specialty",
    "role.backend": "Backend",
    "role.frontend": "Frontend",
    "role.fullstack": "Full Stack",
    "reg.langs": "Languages you use",
    "reg.langs.help": "Select all that apply",
    "dash.kicker": "// Application tracking",
    "dash.title": "Dashboard",
    "dash.subtitle": "Managing BOOTCAMP GITEGA registrations",
    "dash.new": "+ New registration",
    "dash.logout": "Sign out",
    "kpi.total": "Applications",
    "kpi.accepted": "Accepted",
    "kpi.pending": "Pending",
    "kpi.spots": "Spots left",
    "chart.hack": "Candidate profiles",
    "chart.level": "Experience level",
    "table.title": "All applications",
    "table.search": "Search (name, email, group, profile, status…)",
    "table.export.sheet": "Applications",
    "filter.all": "All",
    "filter.pending": "Pending",
    "filter.accepted": "Accepted",
    "filter.waitlist": "Waitlist",
    "filter.rejected": "Rejected",
    "loading": "Loading...",
    "table.empty": "No applications",
    "th.candidate": "Candidate",
    "th.level": "Level",
    "th.hackathon": "Profile",
    "th.avail": "Available 5 days",
    "th.laptop": "Laptop",
    "yes": "Yes",
    "no": "No",
    "th.group": "Group",
    "th.date": "Date",
    "th.status": "Status",
    "status.pending": "Pending",
    "status.accepted": "Accepted",
    "status.waitlist": "Waitlist",
    "status.rejected": "Rejected",
    "login.kicker": "// Admin",
    "login.title": "Sign in",
    "login.subtitle": "Reserved for BOOTCAMP GITEGA organizers.",
    "login.email": "Email",
    "login.password": "Password",
    "login.submit": "Sign in",
    "login.submitting": "Signing in...",
    "login.success": "Signed in!",
  },
};

export function I18nProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("fr");

  useEffect(() => {
    const saved = (typeof window !== "undefined" && localStorage.getItem("lang")) as Lang | null;
    if (saved === "fr" || saved === "en") setLangState(saved);
    else if (typeof navigator !== "undefined" && navigator.language.startsWith("en")) setLangState("en");
  }, []);

  useEffect(() => {
    try { localStorage.setItem("lang", lang); } catch {}
    if (typeof document !== "undefined") document.documentElement.lang = lang;
  }, [lang]);

  const t = (k: string) => dict[lang][k] ?? dict.fr[k] ?? k;
  return <I18nContext.Provider value={{ lang, setLang: setLangState, t }}>{children}</I18nContext.Provider>;
}
export const useI18n = () => useContext(I18nContext);
